testutil/grpc.go
Copied from: https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/testutil/grpc.go
=> feat: add fake grpc server testutil

.github/workflows/go-lint.yml
The golang lint run keeps timing out. These increases the timeout. see https://golangci-lint.run/usage/configuration/#command-line-options
[Example of a timed out run ](https://github.com/abcxyz/jvs/runs/7419521167?check_suite_focus=true)
=> chore: increase timeout

go.mod, go.sum, logging/logger.go, logging/logger_test.go
This adds a new function to the logging package that enables us to couple the logger to the testing context. This will clean up test output and ensure we only see log messages relevant to the failed test(s).
=> Add helper for making a logger tied to a test context

testutil/error.go, testutil/error_test.go
This changes the DiffErrString output to match the existing "expected X to be Y" formatting.
=> Tweak DiffErrString output slightly

mysqltest/docker.go, mysqltest/docker_test.go
The docs for DB.Close() specfically say not to do this. These connections should be long-lived. This bug may be causing problems with connection pooling, causing clients to get "bad connection" errors.
=> fix: don't close DB connection after it's established

testutil/integ.go, testutil/integ_test.go
Use this to skip integration test in unit test so we can run test uniformly with `go test ./...`
```go
func TestMyIntegration(t *testing.T) {
testutil.SkipIfNotIntegration()
// Test stuff
}
```
Follow up - update lumberjack / jvs to use this to skip integration test.
=> feat: add a util to check if it's in an integration test

.github/workflows/go-lint.yml, .golangci.yml, grpcutil/jwt_auth.go, mysqltest/docker.go, mysqltest/mysqltest_test.go, terraform/modules/workload-identity-federation/main.tf, terraform/modules/workload-identity-federation/outputs.tf, terraform/modules/workload-identity-federation/variables.tf, testutil/integ_test.go, testutil/jwt.go, worker/worker.go
This moves the linting configuration into a file and adds a few new linters that were released since the initial design. One of the nicest ones is goheader, which checks that the Apache license header is added to new Go files. Turns out, we had a slight typo that has been copy-pasted around, so I fixed that too.
=> Move linter config into a file, add new linters

.golangci.yml
A single tab should be valid on the `// http://www.apache.org/licenses/LICENSE-2.0` line since that's what gofumpt seems to like to do. The current regex is looking for at least 2 tabs.
=> fix: added more flexibility to the golang-lint regex for header.

timeutil/duration.go, timeutil/duration_test.go, timeutil/timeutil.go
This adds a helper for printing a duration in a "human" form. See the godoc and tests for examples.
=> timeutil: add helper for printing a duration

.github/workflows/terraform-lint.yml
The missing `\n` was causing `sort -u` to not do the "unique" part causing duplicate runs on the same directory.
=> fix terraform lint directories

.github/workflows/terraform-lint.yml
And `GITHUB_ENV` cant do newlines...
=> fix terraform lint

.github/workflows/terraform-lint.yml
This sets an environment variable to tell Terraform that it's running in automation (to prevent prompting for input) and uses "-recursive" on the formatting check to reduce the number of terraform processes spawned.
=> Use recursive to check format and mark "in automation"

renderer/assets.go, renderer/assets_test.go, renderer/funcs.go, renderer/funcs_test.go, renderer/html.go, renderer/html_test.go, renderer/json.go, renderer/json_test.go, renderer/renderer.go, renderer/renderer_test.go
This brings over a bunch of the high-performance and highly-fault-tolerant HTML and JSON rendering from Exposure Notifications, but decouples it from the EN internals. Of note:
- It does not have a dependency on a specific logger and instead allows providing an `onError` handler; there are no dependencies besides the stdlib.
- Reasonable set of built-in functions with the ability to append custom ones.
The package-level comment provides more details and there are some examples of how the package can be used in renderer_test.go.
=> Add general purpose HTML and JSON rendering package

renderer/assets.go, renderer/assets_test.go, renderer/renderer.go
This is a small API change to support rendering individual assets (css and js) in addition to the existing collection of files. It uses a glob pattern to identify files. It also removes the tight coupling from the "assets/static" folder structure.
=> renderer: support rendering single assets

.github/workflows/go-test.yml
Across the board, we're spending more time download and then saving the cache (400MB) instead of just downloading the modules directly on each run.
=> Do not cache Go packages

internal/tools/terraformlinter/terraform_linter.go, internal/tools/terraformlinter/terraform_linter_test.go
Changed the logic for detecting the end of a line to include comment tokens which greedily eat the newline token.
=> fix: closes #83 issue with comments at end of identity tokens

logging/logger.go
This appears to be carry-over from when we extracted this from Lumberjack.
=> Do not use AUDIT_CLIENT prefixes for the logger

githubapp/githubapp.go, githubapp/githubapp_test.go
This allows us to use the same logic for creating installation app tokens from both github-token-minter and github-metrics-aggregator.
=> feat: generalized GitHub app token creation

.github/workflows/want-lgtm-all.yml, README.md
Porting the `want-lgtm-all` workflow from the hackathon. This changes from using labels to using a regex to find the `want_lgtm=all` string in the pull request body.
This also fixes a bug where submitted reviews could be request changes and not approved.
=> add want-lgtm-all reusable workflow

.github/workflows/want-lgtm-all.yml
The lgtm workflow fetches the PR body from the context of the Github Action workflow. This means the body is versioned to the snapshot of whatever the body was at the time the workflow was kicked off. In practice, this can cause an unmergable PR if the tag is removed from the PR. Ex.
1. Create PR with lgtm tag
2. Add reviewers to PR
3. Single reviewer approves -> want_lgtm fails because not all have approved
4. Remove the tag
5. The "pull_request_review" trigger will still fail even if the workflow is re-ran. The workflow still uses the context from when want_lgtm tag was present. Only way to pass the workflow is to add another review, or change the existing review.
Instead, we should fetch the latest version of the Pull Request body when the workflow runs.
=> Fetch pr body from api instead of context

cli/flags.go, cli/flags_test.go
Without this fix, the default value will be ignored in a custom `setter` function.
want_lgtm=@sethvargo
=> Fix CLI flag bug in handling default value with setter

containertest/docker.go
Adding this change replicates the behavior for running with `docker run -p` port mapping, prior to adding this, containertest relies on the Dockerfile declaring exposed ports.
=> Enhancement: Add ExposedPorts to container setup RunOptions

testutil/error.go, testutil/error_test.go
This helps users see at a glance where two errors are different, when errors are large.
To avoid cluttering the output with -got/+want output when unneeded, we guard this logic to only run when either:
- the message sizes are both greater than 20 bytes OR
- the messages are both multiple lines
=> Sometimes, add a -/+ diff to DiffErrString output

.github/actions/override-variables/action.yml, .github/actions/override-workflow-variables/action.yml
This is a reusable GitHub action for loading env variables from an env file of the working-directory, if it exists, into the `GITHUB_ENV` environment file. 
To require the use of an env file, set `require_env = 'true'`  and optionally specify `enforced_directories` (in CSV string) to enforce upon specific directories and their subdirectories. This is useful when you need separated env variables between directories.
=> Add override-workflow-variables action

cli/command.go, cli/command_test.go
When adding prompt feature to https://github.com/abcxyz/abc, I noticed that prompt cannot be canceled with SIGTERM or SIGINT (even it parent context was created that way). This adds that capability.
Chose to add context to prompt func to allow calling function to determine how the context should be canceled in addition to adding signal.NotifyContext to guarantee Prompt is cancelable.
=> fix: allow cli prompt to be canceled

cli/command.go
Using fmt.Print() was causing the output to show the empty args array.
e.g. 
```
fmt.Print(c.Stdout(), "this is a message", []string{}) -> this is a message[]
```
=> fix: prompt should print with Fprintf

cli/flags.go
Since this is really only used to override something in testing, we don't want to push the nil check upstream.
=> cli: don't panic if the lookuper is nil

workerpool/workerpool.go, workerpool/workerpool_doc_test.go, workerpool/workerpool_test.go
This is a breaking change, but it's our internal package. Unfortunately we can't just alias the old package to the new package, because type aliases don't yet support generics.
=> Rename worker to workerpool

workerpool/workerpool.go, workerpool/workerpool_doc_test.go, workerpool/workerpool_test.go
This is a breaking API change, mostly because the "option pattern" with Go doesn't work well with generics. The Option has to carry the type signature (which is fine), but the call site requires specifying the type signature again, and it felt really bad. I'd like:
```go
pool := workerpool.New[string](3, workerpool.WithStopOnError(true))
```
but the Option also needs a type inference:
```go
pool := workerpool.New[string](3, workerpool.WithStopOnError[string](true))
```
And that would need to be repeated for each option...
=> workerpool: add stop-on-error functionality

.github/actions/terraform-linter/action.yml, .github/workflows/go-lint.yml, .github/workflows/go-test.yml, .github/workflows/java-lint.yml, .github/workflows/terraform-lint.yml, .github/workflows/yaml-lint.yml, .golangci.yml, containertest/README.md, mysqltest/README.md
=> Update linters and actions

renderer/json.go, renderer/json_test.go
The previous behavior rendered static JSON for 2xx responses, which might not be desirable for HTTP statuses like 204 (no content).
want_lgtm=all
=> renderer: do not render special json on nil

cli/command.go, cli/command_test.go
`os.GetCwd` isn't _always_ enough, esp with symlinks.
=> cli: add helpers for cwd and execpath

.github/workflows/go-lint.yml
It uses it's own cache: https://github.com/golangci/golangci-lint-action/issues/135
=> test: disable cache for golangci

cli/command.go, cli/command_completions_doc_test.go, cli/command_doc_test.go, cli/command_group_doc_test.go, cli/command_persistent_flags_doc_test.go, cli/command_test.go, cli/flags.go
This adds new helpers for defining the environment. By default, they use the `os` functions. However, they can be overridden (e.g. in tests) with custom values. This also adds a new function on the Command that returns a FlagSet that is configured to use the `LookupEnv` function on the Command.
=> cli: add GetEnv and LookupEnv helpers

sets/maps.go, sets/maps_test.go, sets/sets.go, sets/slices.go, sets/slices_test.go
This introduces some library functions that are not present in `exp/slices` and `exp/maps` today, notably set intersection, union, and subtraction operations.
The package exposes both `slice` and `map` variants, but the `map` functions are named `*MapKeys` to emphasize that set operations are performed on the keys as opposed to the values.
=> sets: introduce sets package for common set-like operations

cli/command.go, cli/command_test.go
Why? In the abc CLI we want to test a function that does multiple rounds of back-and-forth dialog with the user. Currently, this isn't possible, because prompts don't appear in a test environment. `Prompt()`
doesn't write to stdout when stdout is a `*bytes.Buffer` (as created by `BaseCommand.Pipe()`).
How do we do this? We add a type-assertion to check is stdout is a `*io.PipeWriter.` If so, we assume that it's appropriate to print a prompt. Tests that want to see prompt messages can just use `io.Pipe`.
Also, we add  a new test`TestBaseCommand_Prompt_Dialog`, which demonstrates how to write a kind of "conversational" tests using `Prompt()`.
*Alternative considered*: rather than checking for stdout to be a `*io.PipeWriter`, check that it implements some special interface like `type …
=> Support back-and-forth dialogs in Prompt() tests

internal/tools/terraformlinter/terraform_linter.go, internal/tools/terraformlinter/terraform_linter_test.go
Terraform added a new `import` block that should be supported by our linter. Previously it would throw and error if values contained a hyphen but that should be allowed.
=> fix: terraform-linter honors import blocks

cli/command.go, cli/command_test.go
As identified in abcxyz/lumberjack#433, sometimes we need to read the entire value of stdin, until EOF. The current implementation of `Prompt` relies on newline characters for termination. The new implementation has a generic `PromptTo` function that leverages a `bufio.SplitFunc` to customize splitting. It also adds a `PromptAll` function that will read everything until EOF.
This PR also refactors the tests a bit to unify all the tests for a particular function under a single test (with everything else under subtests).
=> cli: add PromptAll and PromptTo

cli/flags.go
This fixes a bug where, on 32-bit operating systems, a large integer value would overflow when boxed from a 64-bit int/uint (from ParseInt/ParseUint) to a 32bit int/uint.
=> Avoid overflowing int and uint on 32-bit systems

buildinfo/buildinfo.go
After https://github.com/abcxyz/abc/pull/149, I feel like we've reached the point where there's significant enough complexity to warrant centralizing this logic.
=> Add helpers for getting version and vcs information

.github/actions/load-workflow-variables/action.yml, .github/actions/load-workflow-variables/test/env.yml, .github/actions/load-workflow-variables/test/local/env.yml, .github/actions/load-workflow-variables/test/multiple/env1.yml, .github/actions/load-workflow-variables/test/multiple/env2.yml, .github/workflows/load-workflow-variables-test.yml
This will help facilitate using multiple service accounts for Guardian in a single repo. The YAML syntax allows us to use YQ to better remove comments and create output for appending to the GitHub environment file.
=> feat: new workflow to load workflow variables from YAML file

.github/actions/load-workflow-variables/action.yml
Previously, the explicit working-directory property and input working directory were conflicting. This change defaults to running this action in the root workspace dir and generates paths from there.
=> fix: working dir for load workflow variables

githubapp/githubapp.go
Allow repositories to be empty to allow tokens to be created for all granted repositories.
=> fix: allow empty token request property

githubapp/githubapp.go, githubapp/githubapp_test.go
Create specific function for calling the GitHub API for generating installation access tokens.
=> fix: specific functions for github access tokens

.github/actions/scancode/action.yml, .github/workflows/scancode.yml, scancode/Dockerfile, scancode/entrypoint.sh
Goal: A Github action/workflow to run on workflow_dispatch on the entire repo to get all licenses, dependencies, and copyrights in a json and csv file.
=> feat: add scancode action and reusable workflow

.github/workflows/create-tag.yml, .github/workflows/go-lint.yml, .github/workflows/go-test.yml, .github/workflows/java-lint.yml, .github/workflows/scancode.yml, .github/workflows/terraform-lint.yml, .github/workflows/yaml-lint.yml, README.md
This provides users more control over the underlying runner image used to when executing a reusable workflow. The defaults are unchanged.
~It's unclear if this will "just work" for object inputs (e.g. `{labels: 'my-runner'}`) for self-hosted runners, or if further JSON incantations will be required.~ It works!
Note: we already had this functionality for the "go-test" reusable workflow, but it was named "os". This PR remove "os" as an input, since it really should have been named "runs-on" in the first place. I searched, and the only existing usage of "os" is [in abcxyz/abc](https://github.com/abcxyz/abc/blob/9e69ab89e7a6af7ee4f389b4a0e1aa75aa4d3f3a/.github/workflows/lint-test.yml#L47), so I will have a PR ready to address the migration once this merges.
=> Add custom "runs-on" key to reusable workflows

logging/logger.go, logging/logger_test.go
This will only apply when the logger is configured with `AddSources`.
=> Use custom sourceLocation field

cmd/terraform-linter/main.go, internal/tools/terraformlinter/terraform_linter.go, internal/tools/terraformlinter/terraform_linter_test.go, internal/tools/terraformlinter/version.go, internal/tools/terraformlinter/violations.go
This refactors the Terraform Linter to make things more typesafe in service of a future PR I am working on. Notably it:
- Switches to using a workerpool to process each file in parallel instead of serial
- Sorts violations (by file, by line, by string) for consistent ordering
- Handles interupts/termination by user input (ctrl+c)
- Moves to concrete violation initializers instead of inline string interpolation; this also brings some type safety, since the function signature has to declare the expected inputs (whereas `fmt.Sprintf` accepts ...any)
- Refactors all the tests to be based on the raw string instead of the constant variable
- Removed `wantError` from tests - it was unused and always false
- Switch to buildinfo package for getting version information
=> Slight refactor to terraform-linter

.github/workflows/create-tag.yml
fix #215 
prevent self-review on deployment has shipped according to https://github.com/github/roadmap/issues/825, it's now on deployment reviewer's hand to check if the tag created on unprotected branches is for valid reasons.
=> Allow create tag on branches that are not default branch

.github/actions/deploy-dataflow-pipeline/action.yml
* Changed action to only call the delete command if the pipeline already exists.
* Made commmand line flag assignments consistent by always using '='
* Made script indentation consistent
=> Only delete pipeline if it exists

.golangci.yml, bqutil/query.go, bqutil/query_test.go, cfgloader/cfgloader_test.go, cli/command_doc_completions_test.go, cli/flags.go, cli/flags_test.go, gcputil/gcputil.go, githubapp/githubapp.go, githubapp/githubapp_test.go, healthcheck/healthcheck.go, internal/tools/terraformlinter/terraform_linter.go, protoutil/conversion_test.go, renderer/funcs_test.go, serving/serving.go, serving/serving_doc_test.go, serving/serving_test.go
Instructions to bring existing repos to this standard:
1. Install gci: `go install github.com/daixiang0/gci@v0.11.2`
2. Run in the repo root `gci write -s standard -s default -s "prefix(github.com/abcxyz)" -s blank -s dot --custom-order --skip-generated .`
=> experiment: add gci to golangci-linters to order/group imports

internal/tools/terraformlinter/terraform_linter.go, internal/tools/terraformlinter/terraform_linter_test.go
This fixes false violations when using moved blocks to refactor terraform. An example of this is when using the moved block to move an IAM resource, whose keys contain hyphens (e.g GCP service accounts).
=> fix: add moved block to token types of terraform linter

gcpmetadata/client.go, gcpmetadata/client_test.go, gcpmetadata/gcpmetadata.go, gcputil/gcputil.go, go.mod, go.sum
This drops the dependency on cloud.google.com/go/compute/metadata, which also drops the dependency tree on cloud.google.com/go/compute. It comes at the expense of introducing go-retry. I could inline the retries if that's desirable.
=> Add gcpmetadata client

.github/actions/terraform-linter/action.yml, .github/workflows/ci.yml, .github/workflows/go-lint.yml, .github/workflows/go-test.yml, README.md, containertest/README.md, mysqltest/README.md
This reduces the number of places to keep Go versions in sync. This is backwards-compatible as `go_version` takes precedence over `go_version_file`.
=> Default Go lint and test to use version from go.mod

.github/actions/create-pull-request/action.yml
Created this enable reuse. This is modified from the secure-setup-terraform repository to generate checksums.
Example usage:
```yaml
- name: 'Create/Update Pull Request'
uses: 'abcxyz/pkg/.github/actions/create-pull-request@main'
with:
token: '${{ secrets.TOKEN }}' # or use github-token-minter
base_branch: 'main'
head_branch: 'automation/test-pr'
title: 'test: testing the create PR flow'
body: |-
Sample creating a multi-line PR body.
Added:
```code
example/exec/test-exec.sh
example/dir/test-file.txt
```
Deleted:
```code
test-file.txt
```
changed_paths: |-
["example/dir/test.txt","example/exec/test.sh"]
deleted_paths: |-
["test-file.txt"]
```
=> feat: add create-pull-request actions

.github/actions/setup-binary/action.yml, .github/workflows/setup-binary-test.yml
Sometimes the downloaded binary wasn't marked as executable (https://github.com/abcxyz/grc/pull/318/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR225).
This fixes the need to have an additional step to mark it with the proper permission.
=> Add chmod +x (executable) to setup-binary action

.github/actions/setup-binary/action.yml
This is needed in the case that the binary does not sit directly in the install_path.
=> Update add_to_path to include binary_subpath

githubauth/app.go, githubauth/app_test.go, testutil/integ_test.go
This fixes a bug where the TokenSource would return the correct value, but the direct invocations would fail.
This is affecting the latest Minty release.
Review the first commit for the nicer diff. The second commit is moving things around so this mistake doesn't happen again: [1dc001b](https://github.com/abcxyz/pkg/pull/291/commits/1dc001ba704668bb010c6e356a655360b34d655e).
=> githubauth: fix response parsing

.github/actions/create-pull-request/action.yml
This change add the ability to create pull requests in draft status.
This change also modifies the existing logic to enable auto merge.
Since both draft and auto-merge are binary states, this change allows the user to toggle the status when creating/updating the pull request and the actions will safely modify.
I ran into several issues with using github-script and the API, namely we have to do a bunch of additional validation against existing states, where the gh cli already does this. I opted for the CLI to not re-invent the wheel and allow for somewhat "cleaner" code.
=> feat: add draft prs to create-pull-request

cli/flags_test.go
DefaultLogger is a shared global, so sometimes this test will fail if the other tests happen to run in an incantation that changes the logger at the same time.
=> Fix race with using DefaultLogger

.github/workflows/draft-release.yml, .github/workflows/release.yml
The `release` workflow is always executed from the default branch, however, the `github.event.workflow_run.head_commit.message` comes from the branch the workflow targets, e.g. `main` or `release/v1`
=> fix: release

.github/workflows/go-lint.yml, .github/workflows/yaml-lint.yml
This is a verbanicm@ trick, but using a multi-line avoids the double-quoting.
=> Switch to nicer quoting for YAML conditions

.github/workflows/go-lint.yml
The lint job takes 30s, and then the cache upload is taking 3 minutes ([example](https://github.com/abcxyz/jvs/actions/runs/8057088187/job/22007480261?pr=398)). I'd like to disable this and see what a cacheless world looks like.
=> Disable caching on golangci

.golangci.yml
In some cases its preferred to use non static messaging.
=> dont enforce static message for sloglint

.github/workflows/want-lgtm-all.yml, README.md
- The GitHub `contains` expression is not case sensitive which allows this to work, saving a job run and an API call [details](https://docs.github.com/en/actions/learn-github-actions/expressions#contains)
- The `edited` status for the review comment only triggers when a review comment body is updated, so it is not needed.
WANT_LGTM=all
=> fix: performance of want_lgtm_all

githubauth/app.go, githubauth/app_test.go
This caches GitHub App Installations after their initial creation, so future invocations return the exact same installation struct without making upstream API calls. To minimize lock contention, values written into the map are closures which are resolved on invocation. This allows parallel goroutines to resolve installations while still maintaining lock integrity.
=> Cache GitHub App Installations

.github/actions/load-workflow-variables/action.yml
This change ensures we check out an approved config file prior to loading the workflow variables.
=> checkout config from default branch in load-workflow-variables action

sets/maps.go, sets/maps_test.go
There was a bug in the old version. The intended behavior was for the the map value to come from the first map in the list. However, the actual behavior was that the map value came from either the first map or from the smallest map, depending on the size order of the input maps.
=> Fix IntersectMapKeys first-wins bug

logging/interceptor.go
`GRPCUnaryInterceptor` returns a [server-side interceptor](https://pkg.go.dev/google.golang.org/grpc@v1.65.0#UnaryServerInterceptor), not client-side.
=> Fix docstring for logging method

.github/actions/load-workflow-variables/action.yml
This change removes the `./` prefix from the input filepath before passing the value onto the following steps. If `./guardian.yml` is provided, then this will be sanitized to `guardian.yml`.
This fixes an issue with `load-workflow-variables` action caused by providing a relative path for `inputs.filepath`, e.g. `./guardian.yml` instead of `guardian.yml`. Passing this value to the `sparse-checkout` option of the Checkout step caused the action to not match with the `guardian.yml` file at the root of the repository, resulting in a file not found error in the `Load Workflow Variables` step.
=> Fix load-workflow-variables issue where config file cannot be found

.github/workflows/ci-docker-test.dockerfile, .github/workflows/ci-docker-test.yml, .github/workflows/maybe-build-docker.yml, README.md
This is a workflow that I have found to be particularly useful for complex CI builds and enables engineers to easily utilize the same images used in the CI environment. Some examples where I have used this workflow:
1) CI builds for cross compilation of embedded software on fpga.
2) CI builds where lengthy installation of dependencies from source is required.
=> feat: add maybe-build-docker.yml workflow

.github/workflows/multi-approvers.js, .github/workflows/multi-approvers.yml, README.md
GitHub reusable workflow to enforce code review requirements, namely that each PR should be reviewed by a member of the organization. This workflow prevents the use of "sock puppet" accounts to work around this requirement by ensuring that PRs originating from outside the org (from a potential sock puppet account) must be approved by at least two in-org members.
Note that we require a JSON file with all members because the token automatically provided to workflows does not allow access to orgs. See [Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).
This members JSON file is problematic because, by definition, the file is stale as soon as it's generated. There …
=> Multi in-org approvals for out-of-org PRs

.golangci.yml, cache/cache.go, cli/command.go, cli/command_doc_test.go, cli/flags.go, cli/flags_test.go, githubauth/app_installation_test.go, multicloser/multicloser_test.go, serving/serving.go
This PR adds support for flags to optionally allow the user to specify special syntaxes that tell the CLI to read the contents from a pipe, prompt, or file. This behavior is off by default and must be enabled on a per-flag basis.
- If a flag sets `AllowFromFile` to true, then if the value for the flag starts with an "@" symbol, the argument is interpreted as a filepath and the contents are read from disk. This is theoretically possible today with shellisms (e.g. `-foo=$(cat bar.txt)`), but this provides a shell-agnostic implementation. If the file does not start with "@", then the value is read as a string as normal. As a special case where the user really wanted the value to be the literal "@", "\\@" can be used to escape the input.
- If a flag sets `AllowFromPrompt` to true, then if the …
=> cli: support "-" and "@" for pipes and files

.golangci.yml
Even with checks, the analyzer can't tell if a precondition was checked, so you end up disabling the linter anyway.
=> Disable overflow checks

.github/workflows/multi-approvers.yml, README.md
Fixes #363, multi-approvers.js not found.
When a reusable workflow uses `require` (via the [github-script](https://github.com/actions/github-script) action) to load a Javascript file, that file must be downloaded (via `curl`) from the git repo.
This PR also fixes another (as yet unreported) bug where the members JSON file would not be loaded correctly. This was caused by the path to the JSON file being incorrect. The root of this issue was a misunderstanding of how the _calling_ and _called_ repos are working together.
1. I've tested similar code in ian-shafer/playground and ian-shafer/playground-2.
2. After the pull request is merged, test using the workflow from ian-shafer/playground (or any other GitHub repo).
=> Fix multi-approvers.js not found bug

.github/actions/create-pull-request/action.yml
This removes the need to manually specify the filepaths that were changed or deleted. It's backwards compatible and requires opt-in via setting "compute_paths: true".
I added a fair amount of debug logging because I suspect there will be some trial and error here...
=> Add auto-compute paths to create-pull-request

.github/actions/create-pull-request/action.yml
Apparently single-line trap works in zsh and newer bash (like my Mac), but not on the version of Bash that exists in GHA. I ran this through ShellCheck and fixed a few linting things.
=> Fix bashisms

.github/actions/create-pull-request/action.yml
Apparently comments are NOT ignored in a condition:
```
2025-01-31T21:57:14.5721570Z ##[debug]....=> false
2025-01-31T21:57:14.5721992Z ##[debug]..=> '# Skip if draft == true, draft PRs cannot modify auto-merge
2025-01-31T21:57:14.5722286Z ##[debug]false'
2025-01-31T21:57:14.5722676Z ##[debug]=> '# Skip if draft == true, draft PRs cannot modify auto-merge
2025-01-31T21:57:14.5723313Z ##[debug]false'
2025-01-31T21:57:14.5724103Z ##[debug]Expanded: (true && '# Skip if draft == true, draft PRs cannot modify auto-merge
2025-01-31T21:57:14.5724445Z ##[debug]false')
2025-01-31T21:57:14.5724904Z ##[debug]Result: '# Skip if draft == true, draft PRs cannot modify auto-merge
2025-01-31T21:57:14.5725211Z ##[debug]false'
```
That shows that the string includes the comment, which evaluates to "true". …
=> Move comment

.github/workflows/multi-approvers.yml, README.md
Allowing `members.json` to be downloaded from any repository, enables configuring multi-approvers as an org-level workflow with a single member list in one place.
=> Support single members.json for entire org

.github/actions/load-workflow-variables/action.yml
https://github.com/abcxyz/pkg/pull/337 changed the behavior of the load-workflow-variables action so that it no longer considers the state of the GitHub workspace when loading the configuration file, but rather it always loads the configuration file from the default branch that was checked out by the `Get Approved Configuration File` step. This change updates the description of the filepath input variable to match.
#337 introduced a breakage for one of our customers. In their workflow, which was using load-workflow-variables from pre-337, they essentially performed the `Get Approved Configuration File` step themselves by checking out the head of their own repository into a subdirectory in their GitHub workspace, then they set `filepath` to a file in that subdirectory. Once the customer …
=> Fix description of filepath input to load-workflow-variables

.github/workflows/create-tag.yml
The current instructions seems a bit out of date. Update it to use minty.
=> fix: update create-tag workflow instructions

cli/flags.go, cli/flags_test.go
Allows users to pass `,` values in their string slice items by escaping them.
Example
`-my-slice-var="This is a message\, please consider,Another message"`
Yields
`[]string{"This is a message, please consider", "Another message"}`
=> feat: handle escaped commas in slicevar flags

logging/logger.go, logging/logger_test.go, logging/targets.go
Log messages need to be able to be differentiated from parseable binary output. Optionally allowing users OR cli/binary authors to set a default log target (STDOUT or STDERR) allows for easier downstream parsing.
Use case:
* tagrep: some warning condition is met but does not prevent continuation/printing out tags. The warning message is logged to stdout - which makes the user have to parse logs from the stdout in order to grab the tags.
* guardian: some warning condition is met but does not prevent fetching entrypoints. Now the user has to know how to parse entrypoints from stdout in order to use them.
NOTE: I considered making the default log target stderr - but given that I don't understand all of the usages I'm not sure this makes sense. Instead I will leave it up to each binary author …
=> feat: allow logging to arbitrary files and stderr

.github/actions/lint-go-modules/action.yml, .github/actions/lint-go/action.yml, .github/actions/lint-java/action.yml, .github/actions/lint-shell/action.yml, .github/actions/lint-terraform/action.yml, .github/actions/lint-yaml/action.yml
New lint actions with the inputs and steps copied from the existing lint workflows.
1. GH Enterprise Server does not support referencing reusable workflows from github.com (even with github connect) - so if we want to leverage the same shared code it must be a shared action.
3. The strategy for [auto linting](https://docs.google.com/document/d/1nJ4wKycxev8d3-FaMwiP4a3YMMVmseofJIPwbwElIaA/edit?resourcekey=0-OYMYvuqjCVlcEbRpvq4O7w&tab=t.0#heading=h.gqscjct0tgq1) on all repositories will require using reusable actions for each linter instead of reusable workflows. This is because we don't know which linters to run without detecting which files are present in a repo - then we utilize github actions matrix syntax to dynamically run each linter.
1. Update the reusable workflows for linting to …
=> chore: create lint actions to replace logic from lint workflows

.github/workflows/want-lgtm-all.yml
Updates the want_lgtm=all check to use tagrep. This allows us to easily support running this check in the merge queue in addition to the pull_request context.
WANT_LGTM=all
=> chore: use tagrep in want-lgtm=all

.github/workflows/ci.yml, .github/workflows/lint-pkg.yml, .github/workflows/lint.yml
Need to update the repo ruleset to add the new required workflows and remove the old ones.
=> chore: switch lint to new workflow

.github/workflows/multi-approvers.js, README.md
Update the README with deprecation date (September 2, 2025) and
migration instructions to the new multi-approvers action.
=> Mark multi-approvers workflow as deprecated

.golangci.yml, default.golangci.yml, logging/logger_test.go
used command "golangci-lint migrate"
This is to fix: https://github.com/abcxyz/github-metrics-aggregator/actions/runs/16375792187/job/46402040201
=> chore: update golangci lint config
