grpcutil/jwt_auth.go, grpcutil/jwt_auth_test.go
follow up from https://github.com/abcxyz/pkg/pull/24
=> feat: switched to option pattern

cfgloader/cfgloader.go
Follow up: https://github.com/abcxyz/pkg/pull/38#issuecomment-1259497798
=> doc: better godoc for cfgloader

logging/logger.go
This caches the call to compute the project ID using a sync.Once. The previous implementation would call the metadata server on each request, effectively adding an additional hop to make the outbound HTTP call.
As an additional optimization, callers can set the PROJECT_ID, GOOGLE_PROJECT, or GOOGLE_CLOUD_PROJECT environment variables to bypass querying the metadata server entirely. This is also useful for local testing.
=> Do not query metadata server on each interceptor call

go.mod, go.sum, protoutil/conversion.go, protoutil/conversion_test.go
fixed unmarshal yaml bug. Previously it can't handle map
=> fix: fixed unmarshal yaml bug

.github/workflows/terraform-lint.yml, internal/tools/terraformlinter/terraform_linter.go, internal/tools/terraformlinter/terraform_linter_test.go
Fixed an issue with the local block causing issues with the following resource block when it contained a reference to one of the special identity tokens.
=> fix: terraform linter issue with local block

.github/workflows/go-lint.yml, cmd/terraform-linter/main.go, internal/tools/terraformlinter/terraform_linter.go, renderer/assets_test.go, renderer/html_test.go, renderer/json_test.go, renderer/renderer.go, renderer/renderer_test.go
=> Input for golangci linter version to allow for pinning

cli/cli.go, cli/cli_doc_test.go, cli/command.go, cli/command_doc_test.go, cli/command_group_doc_test.go, cli/command_persistent_flags_doc_test.go, cli/command_test.go, cli/flags.go, cli/flags_test.go, go.mod, go.sum
This adds the `cli` package which creates well-structured command line interfaces and flag parsing.
=> Add package for creating CLIs

.golangci.yml, serving/serving.go, serving/serving_doc_test.go, serving/serving_test.go
This standardizes our http/grcp server creation and lifecycle handling.
=> Add general-purpose serving infrastructure

.github/workflows/terraform-lint.yml
Fixes https://github.com/abcxyz/gcp-org-terraform-template/pull/22 issue
=> create terraform lint input to prevent walking child dirs

healthcheck/healthcheck.go, healthcheck/healthcheck_test.go
This is significantly faster and safer than relying on the JSON or XML encoders.
=> Use static strings for health checks

cli/flags.go
Closes https://github.com/abcxyz/pkg/issues/127
=> Add time flags

.github/workflows/ci.yml, .github/workflows/yaml-lint.yml, .yamllint.yml
This was for testing and should be removed because I didn't add key sorting.
=> Remove locale

multicloser/multicloser.go, multicloser/multicloser_doc_test.go, multicloser/multicloser_test.go
Alternative approach to https://github.com/abcxyz/pkg/pull/135
=> Add multicloser implementation

cli/command.go, cli/command_test.go
We don't need all these things on the interface
=> cli: slim down the command interface

.github/actions/terraform-linter/action.yml, .github/workflows/terraform-lint.yml
I think this works as intended.
=> lint: use our own terraform linter action

.github/actions/setup-binary/action.yml, .github/workflows/ci.yml, .github/workflows/go-lint.yml, .github/workflows/go-test.yml, .github/workflows/java-lint.yml, .github/workflows/setup-binary-test.yml, .github/workflows/terraform-lint.yml, .github/workflows/want-lgtm-all.yml, .github/workflows/yaml-lint.yml, .yamllint.yml
Also ran `addlicense` to ensure license headers.
=> feat: setup-binary action

.github/workflows/ci.yml, .github/workflows/setup-binary-test.yml
Once we merge this, I need to update the required status checks to use these new names. Do not merge this without me :)
=> Rename CI job names to match other repos

buildinfo/buildinfo.go
This snuck in and made it past review :(
=> Remove log from buildinfo

logging/testing.go
Also apply our custom mutator so the fields match.
=> TestLogger logs at most specific level with sources

gcputil/gcputil_test.go
=> Add some tests

cli/flags.go, cli/flags_test.go
=> Remove defaults when a value is given in maps and slices

.github/actions/load-workflow-variables/action.yml, .github/actions/load-workflow-variables/test/env.yml, .github/actions/load-workflow-variables/test/local/env.yml, .github/actions/load-workflow-variables/test/multiple/env1.yml, .github/actions/load-workflow-variables/test/multiple/env2.yml, .github/actions/load-workflow-variables/test/terraform/deployments/test.txt, .github/actions/load-workflow-variables/test/terraform/experimental/test.txt, .github/actions/load-workflow-variables/test/terraform/org/test.txt, .github/actions/load-workflow-variables/test/terraform/resources/project-a/test.txt, .github/actions/load-workflow-variables/test/terraform/resources/project-b/test.txt, .github/actions/load-workflow-variables/test/terraform/resources/project-c/test.txt, .github/actions/load-workflow-variables/test/test.env.yml, .github/workflows/load-workflow-variables-test.yml
This changes to a single YAML config file instead of an env file per directory. Using the new approach, the config file can be locked down via CODEOWNERS to prevent tampering while additionally allowing CODEOWNERS entries to allow sub-teams to manage their own directories.
```text
env.yml                        owner/admin-team
team/project/environment       owner/project-team
```
Additionally, this new approach allows a * suffix to allow any sub directory to inherit the high level variables.
=> fix: new design for load workflow variables

.github/workflows/create-tag.yml
And also autoformat for line length wrapping it seems
=> Add instructions for using the create-tag.yml scheme

.github/workflows/create-tag.yml
Not sure if I got this right, but I think currently the file dir should be `github-token-minter/deployments/configs/abcxyz`
If I am wrong, please let me know or just close this PR.
Thank you.
=> chore: update comment to reflect the updated dir structure

cli/flags_test.go
I'm not sure why none of the CI jobs caught this until now, but yea, this is a legit race. Fortunately it's only in the test.
=> Fix data race

.github/actions/create-pull-request/action.yml
@verbanicm was right
Although `fromJSON` is simpler than:
```
contains(fromJSON('["true", "True", "TRUE", "1", "T", "t"]'), inputs.add_to_path)
```
😄
=> Use fromJSON to coerce string to boolean

cli/flags_test.go, pointer/pointer.go, pointer/pointer_test.go, renderer/funcs_test.go
We've done this in a bunch of places already...
=> Add generic helpers for pointers

githubauth/app.go, githubauth/app_test.go
This is a breaking API change to account for the added functionality.
Fixes #331
/cc @sqin2019
=> Expand githubauth to pull installation IDs given an org, repo, or user

.github/workflows/maybe-build-docker.yml
This enables using this workflow to push to GAR or GH or both.
=> chore: make gh image optional in maybe-build-docker

cli/command_test.go, cli/flags_test.go, gcpmetadata/client_test.go, githubauth/app_installation_test.go, githubauth/app_test.go, healthcheck/healthcheck_test.go, internal/tools/terraformlinter/terraform_linter_test.go, logging/interceptor_test.go, logging/logger_test.go, pointer/pointer_test.go, protoutil/conversion_test.go, renderer/assets_test.go, renderer/funcs_test.go, renderer/html_test.go, renderer/json_test.go, renderer/renderer_test.go, serving/serving_test.go, sets/maps_test.go, sets/slices_test.go, testutil/error_test.go, timeutil/duration_test.go
This is likely to break anyone using our linter.
=> Do not shadow loop variables anymore

.github/workflows/ci-docker-test.yml, .github/workflows/cleanup.yml, .github/workflows/create-tag.yml, .github/workflows/draft-release.yml, .github/workflows/release.yml
=> Switch to new minty workflow

.github/minty.yaml
We need to use startsWith since we pin SHAs
=> Fix workflow ref

.github/actions/create-pull-request/action.yml
=> mktemp add Xs

.github/actions/create-pull-request/action.yml
`toJSON` creates `'"false"'` which is actually `true` per the rules of Javascript...
=> Ensure action stops if there are no changes

cli/flags.go, cli/flags_test.go
References https://github.com/abcxyz/pkg/pull/411
=> cli: permit escaped slashes in values, remove extra iterations

.github/actions/lint-go/action.yml, .github/actions/lint-shell/action.yml, .github/actions/lint-yaml/action.yml
Fixes https://github.com/abcxyz/pkg/pull/422
=> fix: shell in linters

.github/workflows/want-lgtm-all.yml
Updates so that we do not pull all tags into env vars. Only the ones we care about.
WANT_LGTM=all
=> chore: bump tagrep and explicitly set env var

.github/workflows/create-tag.yml, .github/workflows/draft-release.yml, .github/workflows/go-lint.yml, .github/workflows/go-test.yml, .github/workflows/lint-pkg.yml, .github/workflows/maybe-build-docker.yml, .github/workflows/multi-approvers.yml, .github/workflows/release.yml, .github/workflows/scancode.yml
This is temporary. I'll update for pkg to use the required org linter in a follow up and remove the lint-pkg.yml
=> chore: add ratchet and action linters
